### ISSUE TITLE
Enquiry about the reconstruction loss

### ISSUE THREAD

**Issue by Layne-Huang** [isjakewong/InfoDiffusion#2]
Hi,

Could you please give me some insights about the reconstruction loss in the model? Which part of the loss in the article does this 
 recon loss correspond to? Besides, why do you utilize x0 and epsilon_theta(xt) to obtain x0 in this loss?

Thank you for your attention.

**Comment by isjakewong** [comment]
The reconstruction loss corresponds to the noise matching loss introduced in DDPM (https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://arxiv.org/abs/2006.11239&ved=2ahUKEwjMgaetuaeEAxWskIkEHQChCyMQFnoECBQQAQ&usg=AOvVaw2HvGGcELK1PMuawRxvo7op). x0 is the groundtruth input and epsilon_theta(xt) is the predicted noisy image.
