### ISSUE TITLE
The FID results appear to be abnormal？

### ISSUE THREAD

**Issue by YuSanTu** [isjakewong/InfoDiffusion#3]
I carried out the classification experiment of Fashion-MNIST, and the results matched the results of the original paper. But when I tried to replicate the FID results, there seemed to be something unusual. The following results are obtained: fid: score: 1.852434127158631e-05（on Fashion-MNIST）

**Comment by isjakewong** [comment]
Have you been able to fix this? If not, can you try the dev branch again?

**Comment by YuSanTu** [comment]
> Have you been able to fix this? If not, can you try the dev branch again?
In calc_fid.py file, FID is calculated not by a single directory, but by folder_1 directory where samples are generated and folder_2 directory where samples are sampled from the original data. In this way, the results of FID obtained are relatively close to the paper.

**Comment by isjakewong** [comment]
Right, that's how the FID calculates. The workflow I used is to generate dataset stats first and then calculate FID with sampled images. If you want to use the two-folder way, I think the command in README might miss an argument. Thanks for raising this issue. I'll add a note.

**Comment by YuSanTu** [comment]
Thank you for providing the code and kindly answering, this is a great job.
