### ISSUE TITLE
May I ask where can we find the "ffhq_labels.csv" file

### ISSUE THREAD

**Issue by nina-weng** [isjakewong/InfoDiffusion#4]
Hi :) Thank you for sharing the code! I was wondering where we can find the FFHQ labels, as they are not included in the original dataset. I read from your code that you get them from a CSV file called ffhq_labels.csv. Is there anywhere we can download this, or is it self-annotated by your team?

**Comment by isjakewong** [comment]
Hi, I think you can find FFHQ features from here: https://github.com/DCGM/ffhq-features-dataset

**Comment by YuSanTu** [comment]
> Hi, I think you can find FFHQ features from here: https://github.com/DCGM/ffhq-features-dataset

Thank you for your sharing. In this URL, I find a json folder containing all the image features. Do you convert these json files into a csv table to form a label dataset? Meanwhile, I found that some json files have empty values inside them, such as the 00036.json file. May I ask how you handle these empty value files?

**Comment by nina-weng** [comment]
Thank you for the link @isjakewong !
@YuSanTu  I also found this repo, where they have a csv file for features -- I am not sure whether it is the exact annotations as @isjakewong did but it is easier to use: https://github.com/royorel/FFHQ-Aging-Dataset 

And I hope @isjakewong  can release the csv file as well or detail the pre-processing include the empty value YuSanTu mentioned. Thank you so much!

**Comment by YuSanTu** [comment]
I also extract two csv files from the json folder in the repo shared by @isjakewong. Among them, ffhq_labels-numeral.csv is numeralized for the labels. Also, in eval_disentangle.py, the following modifications are made to remove empty labels and corresponding data:
    elif dataset == "ffhq":
        a = data_dict["all_a"][:, :]
        y = pd.read_csv("ffhq_labels-numeral.csv")
        y = y.iloc[:69952, :]
        valid_rows = ~y.isna().any(axis=1)  # 找到不包含 NaN 的行
        #print(valid_rows)
        a = a[valid_rows]
        y = y.values[valid_rows, :].astype(np.int)

[ffhq_labels.csv](https://github.com/user-attachments/files/18312882/ffhq_labels.csv)
[ffhq_labels-numeral.csv](https://github.com/user-attachments/files/18312883/ffhq_labels-numeral.csv)
